### ISSUE TITLE
Error message for badly formatted yaml

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vscode-direktiv-extension#1]
### Summary

If there are workflow parsing issues the plugin reponds with generic error message: "'direktiv.saveUpdateAndExecute' failed."

On the web UI it provides a more detailed error description: "Failed to update workflow: update workflow: bad workflow definition: yaml: line 7: mapping values are not allowed in this context
"

```
id: caller
functions:
  - id: get
    image: vorteil/request:v2
states:
- id: do
    type: action
    catch:
    - error: ".*"
      transition: jjj
    action:
      function: get
      retries:
        max_attempts: 3
        delay: PT2S
        multiplier: 1.5
        codes: [".*"]
      input: |
        {
          x: 3
        }
  - id: jjj
    type: noop
    log: .
```

**Comment by trentis** [comment]
Now responds with an error in regards to the YAML parsing. Will be out in the release 0.0.7.
