### ISSUE TITLE
Instance output needs more information

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vscode-direktiv-extension#4]
### Summary

The output tab of the instance only shows the log of the instance. It would be good if the workflow output value would be added after the workflow has finished.

**Comment by trentis** [comment]
Changed the way we log now to the file the input/output looks like this now. This will come into play on the 0.0.7 release.  

```
------INPUT-------
{
  "input": ""
}
------LOGS--------
[12:13:05.324] Preparing workflow triggered by API.
[12:13:05.342] Running state logic -- helloworld:1 (noop)
[12:13:05.342] Transforming state data.
[12:13:05.349] Workflow completed.

------OUTPUT------
{"result":"Hello World!"}
```
