### ISSUE TITLE
direktion needs hot keys

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vscode-direktiv-extension#8]
### Summary

direktion needs hotkeys, e.g.:

- convert
- convert & upload
- convert & upload & execute

**Comment by jensg-st** [comment]
and maybe a "force overwrite" if the yaml file already exists

**Comment by trentis** [comment]
- ctrl-alt-c compile yaml file
- ctrl-alt-g compile yaml file and upload
- ctrl-alt-r  compile yaml file, upload and execute the workflow
